<?php

return [
    'bank_account'                => 'Bank Account',
    'bank_occ_account'            => 'Bank OCC A/c',
    'bank_od_account'             => 'Bank OD A/c',
    'branch_division'             => 'Branch / Division',
    'capital_account'             => 'Capital Account',
    'cash_in_hand'                => 'Cash in Hand',
    'current_asset'               => 'Current Asset',
    'current_liabilities'         => 'Current Liabilities',
    'deposit_asset'               => 'Deposit (Asset)',
    'direct_expenses'             => 'Direct Expenses',
    'direct_income'               => 'Direct Income',
    'duties_taxes'                => 'Duties & Taxes',
    'expenses_direct'             => 'Expenses (Direct)',
    'expenses_indirect'           => 'Expenses (Indirect)',
    'fixed_asset'                 => 'Fixed Asset',
    'income_direct'               => 'Income (Direct)',
    'income_indirect'             => 'Income (Indirect)',
    'indirect_expenses'           => 'Indirect Expenses',
    'indirect_income'             => 'Indirect Income',
    'investments'                 => 'Investments',
    'loans_advances_asset'        => 'Loans & Advances (Asset)',
    'loans_liabilities'           => 'Loans (Liabilities)',
    'misc_expenses_asset'         => 'Misc. Expenses (Asset)',
    'provisions'                  => 'Provisions',
    'purchase_account'            => 'Purchase Account',
];
